# This workflow will do a clean install of node dependencies, build the source code and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Master

on:
  push:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install secure-delete
        run: |
          sudo apt update
          sudo apt install secure-delete

      - name: Generate
        run: yarn generate

      - name: Publish Package to GitHub registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_REGISTRY_PUBLISH_TOKEN }}" > ~/.npmrc
          npm publish
          find ~/.npmrc -exec shred -fuz {} +
        env:
          GH_REGISTRY_PUBLISH_TOKEN: ${{ secrets.GH_REGISTRY_PUBLISH_TOKEN }}

      - name: Publish Package to npmjs.org
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTOMATION_TOKEN }}" > ~/.npmrc
          npm publish
          find ~/.npmrc -exec shred -fuz {} +
        env:
          NPM_AUTOMATION_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
