# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: trunk

on:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}.${{ github.sha }}.trunk
  cancel-in-progress: true

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Don't save Bash session history
        run: unset HISTFILE

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            shelltools:
              - 'src/*.sh'

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          check-latest: true

      - name: Get variables (publish)
        id: get-variables
        run: |
          PACKAGE_VERSION=$(jq --raw-output ".version" <./package.json)
          PUBLISHED_PACKAGE_VERSION=$(curl -s https://registry.npmjs.com/material-design-icon-fonts-self-hosted-web/latest | jq --raw-output ".version")
          SHOULD_PUBLISH='false'
          if [ "${PACKAGE_VERSION}" != "${PUBLISHED_PACKAGE_VERSION}" ]; then SHOULD_PUBLISH='true'; fi
          echo "::set-output name=publish::$(echo ${SHOULD_PUBLISH})"

      - name: Lint shell
        if: steps.changes.outputs.shelltools == 'true'
        run: |
          sudo apt install -y shellcheck
          yarn lint

      - name: Install secure-delete
        if: steps.get-variables.outputs.publish == 'true'
        run: sudo apt install -y secure-delete

      - name: Generate
        if: steps.get-variables.outputs.publish == 'true'
        run: yarn install

      - name: Publish the package (npmjs.org)
        if: steps.get-variables.outputs.publish == 'true'
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTOMATION_TOKEN }}" > ~/.npmrc
          npm publish --access public || true
          find ~/.npmrc -exec shred -fuz {} +
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
