# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: trunk-on-push

on:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Don't save Bash session history
        run: unset HISTFILE

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Install secure-delete
        run: |
          sudo apt update
          sudo apt install secure-delete

      - name: Generate
        run: yarn install

      - name: Publish the package (npmjs.org)
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTOMATION_TOKEN }}" > ~/.npmrc
          npm publish --access public || true
          find ~/.npmrc -exec shred -fuz {} +
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
